# Basic example using the MOSM, Conv, CSM and SM-LMC kernels
Here we show the basic usage of the toolkit using a contrived example dataset of three sinusoidal signals. The three sinusses are each put in a channel and have the same frequency but differ in phase. The observations are randomly picked in the range of [0,4], where the first channel will have the second half of the observations removed. Each of the kernels is being evaluated on the same dataset so that we can easily compare the results. Finally, a comparison is made between the different kernels and the errors they obtain.

In [1]:
# import library if it is not installed
import sys
sys.path.insert(0, '../')

import mogptk
import numpy as np

# TODO: remove when done:
%reload_ext autoreload
%autoreload 2

## Generate dataset

In [2]:
data = mogptk.Data()

data.add_function(lambda x: np.sin(6*x), n=20, start=0.0, end=4.0, var=0.03, name='A')
data.add_function(lambda x: np.sin(6*x)+2, n=20, start=0.0, end=4.0, var=0.03, name='B')
data.add_function(lambda x: np.sin(6*x)+2 - np.sin(4*x), n=20, start=0.0, end=4.0, var=0.03, name='C')

data.remove_range('A', start=2.0, end=None)

## MOSM

In [9]:
model_mosm = mogptk.MOSM(data, Q=3)
display(model_mosm.get_params())
model_mosm.estimate_params()
display(model_mosm.get_params())

[{'magnitude': array([0.60165505, 0.43129299, 0.31466658]),
  'mean': array([[ 0.55368507, -1.21678965,  0.73240389]]),
  'variance': array([[0.4028232 , 0.96761288, 0.01520945]]),
  'delay': array([[0., 0., 0.]]),
  'phase': array([0., 0., 0.]),
  'noise': array([0.29080653, 0.16220372, 0.68134703])},
 {'magnitude': array([-0.99632054,  2.8567706 , -1.42035188]),
  'mean': array([[-0.40018327, -0.24111434, -0.31260152]]),
  'variance': array([[0.65336648, 0.09336869, 0.5669838 ]]),
  'delay': array([[0., 0., 0.]]),
  'phase': array([0., 0., 0.]),
  'noise': array([0.74514307, 0.6033652 , 0.57624663])},
 {'magnitude': array([-0.11044569, -0.7034589 ,  0.47207935]),
  'mean': array([[-0.65362344,  0.16680292, -0.56969792]]),
  'variance': array([[0.89728699, 0.50354221, 0.848873  ]]),
  'delay': array([[0., 0., 0.]]),
  'phase': array([0., 0., 0.]),
  'noise': array([0.86247205, 0.88070909, 0.48503308])}]

Building...


Optimizing...
Optimization terminated successfully.
         Current function value: -16.969494
         Iterations: 34
         Function evaluations: 42
         Gradient evaluations: 42
INFO:tensorflow:Optimization terminated with:
  Message: Optimization terminated successfully.
  Objective function value: -16.969494
  Number of iterations: 34
  Number of functions evaluations: 42
Done
[[ 0.55368507 -1.21678965  0.73240389]] [1.e-06]
[[-0.40018327 -0.24111434 -0.31260152]] [0.00370827]
[[-0.65362344  0.16680292 -0.56969792]] [0.95527538]
Building...


Optimizing...
Optimization terminated successfully.
         Current function value: 1.227931
         Iterations: 136
         Function evaluations: 161
         Gradient evaluations: 161
INFO:tensorflow:Optimization terminated with:
  Message: Optimization terminated successfully.
  Objective function value: 1.227931
  Number of iterations: 136
  Number of functions evaluations: 161
Done
[[1.e-06 1.e-06 1.e-06]] [1.e-06]


IndexError: index 1 is out of bounds for axis 0 with size 1

In [ ]:
model_mosm.train(disp=True)
display(model_mosm.get_params())

In [ ]:
model_mosm.set_prediction_range(channel='A', start=0, end=4, step=0.02)
model_mosm.set_prediction_range(channel='B', start=0, end=4, step=0.02)
model_mosm.set_prediction_range(channel='C', start=0, end=4, step=0.02)
model_mosm.predict()

mogptk.plot(model_mosm)

## CSM

In [ ]:
model_csm = mogptk.CSM(data, Q=3)
model_csm.build()
model_csm.optimize()

In [ ]:
model_csm.set_prediction_range(channel='A', start=0, end=4, step=0.02)
model_csm.set_prediction_range(channel='B', start=0, end=4, step=0.02)
model_csm.set_prediction_range(channel='C', start=0, end=4, step=0.02)
model_csm.predict()

mogptk.plot(model_csm)

## CG

In [ ]:
model_cg = mogptk.CG(data, Q=3)
model_cg.build()
model_cg.optimize()

In [ ]:
model_cg.set_prediction_range(channel='A', start=0, end=4, step=0.02)
model_cg.set_prediction_range(channel='B', start=0, end=4, step=0.02)
model_cg.set_prediction_range(channel='C', start=0, end=4, step=0.02)
model_cg.predict()

mogptk.plot(model_cg)

## SM-LMC

In [ ]:
model_smlmc = mogptk.SM_LMC(data, Q=3)
model_smlmc.build()
model_smlmc.optimize()

In [ ]:
model_smlmc.set_prediction_range(channel='A', start=0, end=4, step=0.02)
model_smlmc.set_prediction_range(channel='B', start=0, end=4, step=0.02)
model_smlmc.set_prediction_range(channel='C', start=0, end=4, step=0.02)
model_smlmc.predict()

mogptk.plot(model_smlmc)

## Error estimation

In [ ]:
mogptk.errors(model_mosm, model_csm, model_smlmc, model_cg, print=True)